os: linux
dist: xenial
language: ruby
cache: bundler
before_install: bundle -v
script: bundle exec rake
matrix:
  fast_finish: true
  include:
  - rvm: '2.7'
    env: PUPPET_GEM_VERSION='https://github.com/puppetlabs/puppet.git#main' # TODO: change to 7 once it becomes available
  - rvm: '2.6'
    env: PUPPET_GEM_VERSION='~> 6.0' COVERAGE=yes
  - rvm: '2.5'
    env: PUPPET_GEM_VERSION='~> 6.0' COVERAGE=yes
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 6.0' COVERAGE=yes
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 6.0'
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 5.0' COVERAGE=yes
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 5.0'
  - rvm: '2.4'
    env: PUPPET_GEM_VERSION='~> 4.0' COVERAGE=yes
  - rvm: '2.3'
    env: PUPPET_GEM_VERSION='~> 4.0'
  - rvm: '2.1'
    env: PUPPET_GEM_VERSION='~> 4.0'
notifications:
  email: false
